# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
data:
  barcodes: data/barcode.csv
  samples: data/sample.csv
  units: data/unit.csv
  sample-barcode: data/sample-barcode.csv
  sample-unit: data/sample-unit.csv

ref:
  annotation:
  assembly:
  index:

params:
  fastp:
    I: "-A -p -n 4 -l 16 -P 20 -Y 50"
    R: "-c -p"
  starcode: "-d4 --seq-id"
  
threads:
  fastp: 2
  starcode: 4